# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    
stages:
  - test
  - package
  - deploy

test:
  stage: test
  before_script:
    - apt-get install -y make g++ libxml2-dev libxslt-dev libffi-dev libssl-dev cvs git maven
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install --requirement test-requirements.txt
    - pip install --requirement requirements.txt --extra-index-url $PYPI_URL
  script:
    - coverage run --source=src setup.py test
    - coverage html
    - coverage report --show-missing
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 day

package_wheel:
  stage: package
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/*.whl

package_sdist:
  stage: package
  script:
    - python setup.py sdist
  artifacts:
    paths:
    - dist/*.tar.gz

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $PYPI_URL dist/*
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install twine
  script:
    - twine upload --repository-url $PYPI_URL dist/*
  only:
    - tags
  when: manual
