#
# Reference: https://docs.gitlab.com/ee/ci/yaml/#include
#
# BEWARE: The syntax below is only available from 11.7 and therefore can not be used
# - project: 'my-group/my-project'
#   file: '/templates/.gitlab-ci-template.yml'
#include:
#  - 'https://raw.githubusercontent.com/rostskadat/CiCdTemplates/master/.gitlab-ci-python.yml'

# 
image: 791682668801.dkr.ecr.eu-west-1.amazonaws.com/repo/cicd-python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  TWINE_USERNAME: $PYPI_USERNAME
  TWINE_PASSWORD: $PYPI_PASSWORD

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    
stages:
  - build
  - package
  - deploy

build:
  stage: build
  before_script:
    - pip install --requirement test-requirements.txt
    - pip install --requirement requirements.txt --extra-index-url $PYPI_URL
  script:
    - coverage run --source=src setup.py test
    - coverage xml
    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_USERNAME -Dsonar.password=$SONAR_PASSWORD || sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_USERNAME -Dsonar.password=$SONAR_PASSWORD
    - coverage report --show-missing
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

package wheel:
  stage: package
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
    - dist/*.whl

package sdist:
  stage: package
  script:
    - python setup.py sdist
  artifacts:
    paths:
    - dist/*.tar.gz

deploy staging:
  stage: deploy
  script:
    - twine upload --repository-url $PYPI_URL dist/*
  except:
    - tags

deploy production:
  stage: deploy
  script:
    - twine upload --repository-url $PYPI_URL dist/*
  only:
    - tags
  when: manual
